export const SET_SEARCH = "SET_SEARCH";

export const FETCH_ARTICLES_PENDING = "FETCH_ARTICLES_PENDING";
export const FETCH_ARTICLES_FULFILLED = "FETCH_ARTICLES_FULFILLED";
export const FETCH_ARTICLES_REJECTED = "FETCH_ARTICLES_REJECTED";
